game/urls.py
from django.urls import path
from django.conf.urls import url, include


from . import views

app_name = 'game'

urlpatterns = [
    path('', views.home_page, name='index'),
    path('logout/', views.views_logout, name='logout'),
    path('form/',views.form_page, name="form"),
    path('home/', views.home_page, name='home'),
    path('<int:question_id>' , views.discard_form, name='discard'),
    path('preview',views.preview_form, name='preview'),
    path('stat/', views.get_stat, name='stat'),
    path('statistic/',views.statistic_page, name='statistic'),
    path('howtoplay/', views.how_to_play_page, name='howtoplay'),                 
    path('topic/', views.topic_page, name='topic'),
    path('<int:topic_id>/', views.question_page, name='question'),
    path('receive/<int:topic_id>/', views.receive_score, name='receive'),
    path('<int:question_id>/edit/', views.edit_form, name='edit'),
]
  

thor/urls.py
from django.contrib import admin
from django.conf.urls import handler404, url, include
from django.urls import path, include
import game.views as views


handler404 = 'game.views.page404'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include("game.urls")),
    path('o/', include('social_django.urls', namespace='social')),
    path('', views.index),
]

game/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    topic_name = models.CharField(max_length=100)

    class Meta:
        db_table = 'game_topic'

    def __str__(self):
        return self.topic_name


class Question(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    
    difficulty = models.CharField(max_length=10)

    question_title = models.CharField(max_length=256,
    verbose_name='Title')
    question_text = models.TextField(verbose_name='Question')



    def __str__(self):
        return self.question_title

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=100)
    hint_text = models.CharField(max_length=1000000)

    def __str__(self):
        return self.answer_text


class Statistic(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class UserPicture(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_photo = models.CharField(max_length=10000)


def save_picture(backend, user, response, details,*args,**kwargs):
    if not UserPicture.objects.filter(user=user):
        new_user_pic = UserPicture(user=user, profile_photo=response['picture'])
        new_user_pic.save()

class Best_score(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    key = models.CharField(max_length=100)
    value = models.IntegerField(default=0)

    def __str__(self):
        return self.key

game/forms.py
from django import forms
from django.utils.safestring import mark_safe
from game.models import Answer, Topic, Question

select_difficulty = [
    ('easy','Easy'),
    ('normal','Normal'),
    ('hard','Hard'),
    ('extreme','Extreme'),
]

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = '__all__'
        widgets = {
            'topic':forms.Select(
                attrs={
                'id': 'topic',
                'style' : 'height: 50px; font-size: 20px;',
                'class' : 'col-10 mt-2 p-4 d-flex justify-content-center',
                }
            ),
            'difficulty':forms.Select(
                choices=select_difficulty,
                attrs={
                    'id': 'difficulty',
                    'style' : 'height: 50px; font-size: 20px;',
                    'class' : 'col-10 mt-2 p-4 d-flex justify-content-center',
                }
            ),
            'question_title': forms.Textarea(
                attrs={
                    'id': 'title',
                    'style' : 'height: 50px; font-size: 18px; resize: none',
                    'class' : 'col-10 mt-2 p-3 d-flex justify-content-center',
                }
            ),
            'question_text':forms.Textarea(
                attrs={
                    'id': 'question',
                    'style' : 'height: 750px; font-size: 18px; border-radius: 3%',
                    'class' : 'col-10 mt-2 p-4 d-flex justify-content-center',
                }
            )
        }

class AnswerForm(forms.Form):
    answer = forms.CharField(label=mark_safe(''))

    def __init__(self, *args, **kwargs):
        ans_length = kwargs.pop('ans_length')
        box_length = kwargs.pop('box_length')
        hint = kwargs.pop('hint')
        super(AnswerForm, self).__init__(*args, **kwargs)
        self.fields['answer'].widget = forms.TextInput(
            attrs={
                'id': 'answer',
                'style': 'height: 28px; font-size: 22px; ',
                'size': box_length,
                'maxlength': ans_length,
                'title': hint,
                'onblur': 'checkAnswer()',
            })

class AForm(forms.Form):
    c = forms.ChoiceField(choices=(("a","A"), ("b", "B")), disabled=True)
    

game/views.py
from random import sample
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Lower
from .forms import QuestionForm, AnswerForm
from .models import Question, Statistic, Topic, Answer, Best_score, UserPicture
import logging

# Create your views here.

logger = logging.getLogger('thor')

def get_client_ip(request):
    get_ip = request.META.get('HTTP_X_FORWARDED_FOR')
    if get_ip:
        ip = get_ip.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

def index(request):
    """Redirect to index page."""
    if str(request.user) == 'AnonymousUser':
        client_ip = get_client_ip(request)
        logger.error('Access from {}'.format(client_ip))
    return HttpResponseRedirect(reverse("game:index"))


def page404(request, exception):
    """Redirect to 404 page."""
    client_ip = get_client_ip(request)
    logger.error('response status code 404 from {}'.format(client_ip))
    return render(request, 'game/404.html')

def views_logout(request):
    """User logout and redirect to homepage."""
    user = request.user
    client_ip = get_client_ip(request)
    logger.info('Logout from {}'.format(user))
    logout(request)
    return redirect("game:home")

def home_page(request, error: str=''):
    user = request.user
    """Redirect to homepage."""
    if str(request.user) == 'AnonymousUser':
        client_ip = get_client_ip(request)
        logger.error('Access from {}'.format(client_ip))
    else:
        logger.info('Access from {}'.format(user))
    topic = Topic.objects.all()
    all_best_score = Best_score.objects.order_by('-value')
    return render(request, 'game/home.html', {'all_topic': topic, 'best': all_best_score, 'number': range(1, 11), 'super_user': error})

@login_required
def form_page(request):
    """Redirect to Add Question Form page."""
    user = request.user
    if str(request.user) == 'AnonymousUser':
        client_ip = get_client_ip(request)
        logger.error('Try to access from {}'.format(client_ip))
    logger.info('Access from {}'.format(user))
    form = QuestionForm()
    context = {'form': form}
    return render(request, 'game/form.html', context)

@login_required
def statistic_page(request):
    user = request.user
    client_ip = get_client_ip(request)
    if str(request.user) == 'AnonymousUser':
        logger.error('Try to access from {}'.format(client_ip))
    logger.info('Access from {}'.format(user))
    statistic = get_object_or_404(Statistic, user=request.user)
    picture = get_object_or_404(UserPicture, user=request.user)
    score_for_user = Best_score.objects.filter(user=request.user)
    return render(request, 'game/statistic.html', {'stat': statistic,'pic': picture, 'user_score': score_for_user})

def how_to_play_page(request):
    user = request.user
    client_ip = get_client_ip(request)
    if str(request.user) == 'AnonymousUser':
        logger.error('Try to access from {}'.format(client_ip))
    logger.info('Access from {}'.format(user))
    return render(request, 'game/howto.html')
    

@login_required
def topic_page(request):
    """Redirect to Select Topic page."""
    user = request.user
    client_ip = get_client_ip(request)
    if str(request.user) == 'AnonymousUser':
        logger.error('Try to access from {}'.format(client_ip))
    logger.info('Access from {}'.format(user))
    topic = Topic.objects.all()
    return render(request, 'game/topic.html', {'topic':topic})


def question_difficulty(value: Question, topic_id: int, difficulty: str):
    """Return list of Question with filtered topic_id and difficulty."""
    return [q for q in value.objects.filter(topic_id=topic_id, difficulty=difficulty)]

def sample_question(value: Question, topic_id: int, diff: str, no_of_question: int):
    """
        Return a list of shuffled 'no_of_question' Question(s)
        with filtered topic_id and difficulty.
    """
    each_question_diff = question_difficulty(value, topic_id, diff)
    try:
        shuffle = sample(each_question_diff, no_of_question)
    except ValueError:
        shuffle = sample(each_question_diff, len(each_question_diff))
    return shuffle


def random_question_list(value, topic_id: int):
    """
        Return a list of all 10 (or less) shuffled Question(s)
        with filtered topic_id.
    """
    question_list = []
    for diff in ['easy', 'normal', 'hard']:
        shuffle = sample_question(value, topic_id, diff, 3)
        question_list += shuffle
    question_list += sample_question(value, topic_id, 'extreme', 1)
    return question_list

def create_answer_box(value: str):
    """Replace '[[__|__]]' with input tag.
    Return the formatted value."""
    while ']]' in value:
        start = value.find('[[')
        mid = value.find('|')
        end = value.find(']]')
        ans_length = mid - start - 2
        box_length = ans_length
        if box_length < 1:
            box_length = 1
        hint = value[mid+1:end]
        replacement = str(AnswerForm(ans_length=ans_length,
                                     box_length=str(box_length)+"ch", hint=hint))
        value = value[:start] + replacement + value[end+2:]
    return value

def question_page_resources(topic_id):
    questions = random_question_list(Question, topic_id)
    q_title = [q.question_title for q in questions]
    q_text = []
    for q in questions:
        boxed_question = create_answer_box(q.question_text)
        q_text.append(boxed_question)
    q_diff = [q.difficulty for q in questions]
    ans, hint = [], []
    for question in questions:
        answer_set = list(Answer.objects.filter(
            question_id=question.id, topic_id=topic_id))
        ans.append([a.answer_text for a in answer_set])
        hint.append([a.hint_text for a in answer_set])
    resources = {"title": q_title, "text": q_text,
                 "diff": q_diff, "answer": ans, "hint": hint}
    return resources

@login_required
def question_page(request, topic_id):
    """Redirect to the Game page."""
    user = request.user
    client_ip = get_client_ip(request)
    if str(request.user) == 'AnonymousUser':
        logger.error('Access from {}'.format(client_ip))
    logger.info('Access from {}'.format(user))
    resources = question_page_resources(topic_id)
    get_best_score(request, topic_id)
    return render(request, 'game/game.html', {
        'q_title': resources["title"], 'q_text': resources["text"],
        'answer': resources["answer"], 'hint': resources["hint"],
        'q_diff': resources["diff"], 'topic_id': topic_id})

def assign_answer(value, question_id, topic_id):
    """From 'value', Save string inside '[[__|__]]' as Answer."""
    last_box_mark = 0
    while ']]' in value:
        start = value.find('[[', last_box_mark)
        if start < last_box_mark:
            break
        mid = value.find('|', last_box_mark)
        end = value.find(']]', last_box_mark)
        answer = Answer(question_id=question_id, topic_id=topic_id,
                        answer_text=value[start+2:mid], hint_text=value[mid+1:end])
        answer.save()
        last_box_mark = end + 1

@login_required
def get_stat(request):
    """Create statistic for each player include score"""
    name = request.user
    logger.info("Check player {} info".format(name))
    user_id = request.user.id
    status = True
    check_id = Statistic.objects.filter(user_id=user_id)
    if check_id:
        status = False
        logger.error("{} stat is already exist".format(name))
    if User.is_authenticated and status:
        logger.info("Create stat for {}".format(name))
        user = User.objects.get(pk=user_id)
        stat = Statistic(user=user)
        stat.save()
    try:
        next_page = request.GET['next']
        return HttpResponseRedirect(next_page)
    except:
        return redirect('game:home')

@login_required
def preview_form(request):
    """Reidrect to Form Preview page."""
    name = request.user
    logger.info("Create question from {}".format(name))
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            topic = Topic.objects.get(pk=int(form.data.get('topic')))
            title = form.data.get('question_title')
            raw_question = form.data.get('question_text')
            difficulty = form.data.get('difficulty')
            question = Question(topic=topic,
                                question_title=title,
                                question_text=raw_question,
                                difficulty=difficulty)
            question.save()
            assign_answer(raw_question, question.id, topic.id)
            return render(request, "game/preview_form.html", {'question': question})

@login_required
def discard_form(request, question_id):
    """Discard the Question Form."""
    name = request.user
    logger.info("Delete a question from {}".format(name))
    check = Question.objects.filter(pk=question_id)
    if check:
        question = Question.objects.get(pk=question_id)
        question.delete()
        return redirect("game:form")
    return preview_form(request.POST)

@login_required
def receive_score(request, topic_id):
    """Save highscore to User profile when the game finished."""
    user_id = request.user.id
    topic = get_object_or_404(Topic, pk=topic_id)
    profile = Best_score.objects.get(user=user_id, key=topic.topic_name)
    check_key = Best_score.objects.filter(key=topic.topic_name, user=user_id)
    if check_key:
        try:
            score = request.GET.get('result_score')
            logger.info("Player receive {} score".format(score))
            if int(profile.value) < int(score):
                profile.value = int(score)

game/templates/game/base.html
{% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'game/my_style.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link rel = "stylesheet" type = "text/css" href="{% static 'game/my_style.css' %}">

    <link  rel="stylesheet" href="https://fonts.googleapis.com/css?family=Baloo+Bhai|Orbitron|Mallanna&display=swap">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous"></script>


    
    <script src="https://kit.fontawesome.com/b7f2372ef6.js" crossorigin="anonymous"></script>


    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="font-size: 18px; opacity: 80%">
        <img src="{% static 'game/head.png' %}" alt="Thor Icon" width="40" class="mr-3 ml-1 py-1">
        <a class="navbar-brand" href="#">THOR: The God of Thunder</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto mt-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'game:home' %}">Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'game:howtoplay' %}">Instruction<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link ml-auto btn btn-secondry" href="{% url "game:logout" %}">Logout</a>
                    </li>
                    <li class="nav-item mt-auto">
                        <p  class="text-white ml-auto mt-2">Logged in as {{ user.username }}</p>
                    </li>
                </div>
            </div>
            {% else %}
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">
                    <li class="nav-item active mt-auto">
                        <a class="nav-link" href="{% url 'game:home' %}">Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'game:howtoplay' %}">Instruction<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item mt-auto">
                        <a class="nav-link btn btn-primary" href="{% url "social:begin" "google-oauth2" %}?{{ request.GET.urlencode}}"><i class="fab fa-google" ></i><span class="sr-only">(current)</span></a>
                    </li>
                </div>
            </div>
        {% endif %}
    </nav>
    
    <div class="container-fluid medium_container">
<!--    <div class ="nav-bar"></div>-->
    {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

game/templates/game/form.html
{% extends 'game/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'game/form_page_style.css' %}">

<h1 class="mt-4 pt-5 form">Create question</h1>
<div class="mt-5 container">
  <div class="mt-5 row">
    <div class="col-8">
      <center>
        <form action='{%url "game:preview"%}' method="post">
          {% csrf_token %}
          <div class="form-group  has-feedback">
            <h4 class="text-white">{{ form.as_p }}</h4>
            <button id="submit-form" class="mt-3 mb-5 form btn-light" type="submit">Next</button>
          </div>
        </form>
      </center>
    </div>
    <div class="col-4">
      <p id="suggestion" class="p-4 form_box"> 
        <b>Step 1:</b><br>Select the topic you wish to add your question to.<br>
        <b>Step 2:</b><br>Select the difficulty for you question.<br>
        <b>Step 3:</b><br>Add a title for your question.<br>
        <b>Step 4:</b><br>Write your question/article inside the question box and follow the instruction below to manage how the question will be displayed<br><br>
        QUESTION BOX FORMAT<br>
        Use the following format to create a fill-in the blank boxes.<br><br>
        <mark>[[fill the answer here|fill the hint here]]</mark><br><br>
        You can also leave the hint area empty.<br><br>
        <mark>[[fill the answer here|]]</mark><br><br>
        If you want to add any of the following you need to use these format.<br><br>
        <table>
          <tr>
            <th>Tab</th>
            <th>2 spaces</th>
            <th>New line</th>
          </tr>
          <tr>
            <td><b><mark>&amp;emsp;</mark></b></td>
            <td><b><mark>&amp;ensp;</mark></b></td>
            <td><b><mark>&lt;br&gt;</mark></b></td>
          </tr>
        </table>
        <br>
        Example:<br>
        What part of an if statement should be indented?<b>&lt;br&gt;</b><br>
        Ans: The statements <b>[[within|inside]]</b> it<b>&lt;br&gt;</b><br>
        <b>&lt;br&gt;</b><br>
        >>> num = 12:<b>&lt;br&gt;</b><br>
        >>> if <b>[[num > 5|]]</b>:<b>&lt;br&gt;</b><br>
        ...<b>&amp;emsp;</b>print(“Larger than 5”)<b>&lt;br&gt;</b><br>
        ...if num <=  47:<b>&lt;br&gt;</b><br>
        ...<b>&amp;emsp;</b>print(“Between 5 and 47”)<b>&lt;br&gt;</b><br>
        <b>[[Larger than 5|]]</b><b>&lt;br&gt;</b><br>
        Between 5 and 47<b>&lt;br&gt;<b><br>
      </p>
    </div>
  </div>
<div>

{% endblock  %}

game/templates/game/home.html
{% extends "game/base.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'game/my_style.css' %}">

{% block content %}
{% if user.is_authenticated %}
<script>

    function change_data() {
        document.getElementById('name_10').innerHTML = " ";
        var x = document.getElementById("select_topic").value;
        var rank_num = 1;
        empty_data();
        {% for each_score in best %}
            var topic_text = "{{ each_score.key }}";
            if (x == topic_text) {
                if (document.getElementById('name_10').innerHTML == '') {
                    var name_id = "name_" + rank_num;
                    var name_score = "num_" + rank_num;
                    document.getElementById(name_id).innerHTML = "{{ each_score.user }}";
                    document.getElementById(name_score).innerHTML = "{{ each_score.value }}";
                }
                if ('{{ each_score.user }}' == '{{ user }}') {
                    document.getElementById('user_rank').innerHTML = rank_num ;
                    document.getElementById('user_score').innerHTML = {{each_score.value}};
                }
                rank_num++;
            }
        {% endfor %}
    }

    function empty_data() {
        document.getElementById('user_rank').innerHTML = '';
        document.getElementById('user_score').innerHTML = '';
        var i;
        for (i = 1; i < 11; i++) {
        var name_id = "name_" + i;
        var name_score = "num_" + i;
        document.getElementById(name_id).innerHTML = "";
        document.getElementById(name_score).innerHTML = "";
    }
    }

</script>

    <h1 class="authhome mt-3 pt-5">Thor: The God of Thunder</h1>
    {% if user_score != '' %}
        <h1> {{ user_score }}</h1>
    {% endif %}
    <div class="my-3 container text-white">
        <div class="mb-3 row d-flex justify-content-around align-content-center">
            <div class="col-5">
                <div class="row scoreboard d-flex justify-content-left">
                    <div class="col-6 d-flex justify-content-center">
                        <div class="row align-content-center" style="font-size: 20px"> TOPIC </div>
                    </div>
                    <div class="col-6 d-flex justify-content-center">
                        <select class="browser-default custom-select" id = "select_topic" onchange="change_data()">
                            <option selected>Select topic</option>
                            {% for each_topic in all_topic %}
                            <option value="{{ each_topic.topic_name }}"> {{each_topic.topic_name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-5"></div>
        </div>
        <div class="row justify-content-around">
            <div class="col-5 scoreboard">
                <div class="row  mt-2 d-flex justify-content-center">
                    <h3 class="mt-1">TOP 10 SCOREBOARD</h3> 
                </div>
                <div class="row d-flex justify-content-center">
                    <div class="col-4 d-flex justify-content-center">
                        <div class="row"> RANK </div>
                    </div>
                    <div class="col-4 d-flex justify-content-center">
                        NAME
                    </div>
                    <div class="col-4 d-flex justify-content-center">
                        SCORE
                    </div>
                </div>
                {% for num in number %}
                <div class="row d-flex justify-content-center">
                    <div class="col-4 d-flex justify-content-center">
                        <div class="row"> {{num}} </div>
                    </div>
                    <div class="col-4 d-flex justify-content-center" id="name_{{num}}">
                    </div>
                    <div class="col-4 d-flex justify-content-center" id="num_{{num}}">
                    </div>
                </div>
                <br>
                {% endfor %}
                <div class="row d-flex justify-content-center" style="padding-top: 3%">
                </div>  
            </div>
            
            <div class="col-5">
                <div class="row d-flex justify-content-center">
                    <center><img class="img-responsive" src="{% static 'game/icon.gif' %}" alt="Thor Icon" height="350"></center>
                </div>
                <div class="row d-flex justify-content-center my-3">
                    <button type="button" class="playnow btn col-11" onclick="window.location.href='{% url 'game:topic' %}'">Play Now</button>
                </div>
                <div class="row d-flex justify-content-around my-3">
                    <button type="button" class="home btn col-5" onclick="window.location.href='{% url 'game:statistic' %}'">Player Stats</button>
                
                    <button type="button" class="home btn col-5" onclick="window.location.href='{% url 'game:form' %}'">Create Question</button>
                </div>
                <div class="row d-flex justify-content-center scoreboard mt-2">
                    <div class="col-5 d-flex justify-content-center">
                        RANK
                    </div>
                    <div class="col-5 d-flex justify-content-center">
                        SCORE
                    </div>
                        <div id="user_rank" class="col-5 d-flex justify-content-center">
                        </div>
                        <div id="user_score" class="col-5 d-flex justify-content-center">
                        </div>
                </div>
                                    </div>

            </div>
        </div>
     </div>
{% else %}
    <center>
    <h1 class="mt-5 pt-5 home">THOR</h1>
    <h2 class="home">The God of Thunder</h2>
    <img src="{% static 'game/icon.gif' %}" alt: "Thor Icon" style="height: 300; width: auto" id="iconhome">
    <div class="mt-3 row justify-content-center">    
        <div class="mt-3 col-2 d-flex justify-content-center">
            <button id="google-login" type="button" class="btn login" onclick="window.location.href='{% url "social:begin" "google-oauth2" %}'">Login with <i class="ml-1 fab fa-google" ></i></button>
        </div>
    </div>
    </center>
{% endif %}
{% endblock %}

game/templates/game/howto.html
{% extends "game/base.html" %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'game/howto_style.css' %}">

<div class="container">
    <div class="mt-3 row d-flex justify-content-center"> 
        <div class="mt-5 col-2" style="padding-top: 12%; padding-right: 17%"> 
            <img src="{% static 'game/icon.gif' %}" alt="Thor Icon" height="300" width="auto" style="padding-top:10%" id="iconhowto">
        </div>
        <div class="col-8">  
            <h1 class="pt-5 mt-5 howto">How to play</h1>
            <p class="p-4 mt-5 howto_box"> 
                This is an Educational Game where players have to correctly answer a series of fill-in the blank questions in order to advance 
                to the next level. There are 10 levels in total and passing each level is worth a specific amount of points. There will be a 
                time limit according to the question’s difficulty for the player to come up with the answers. The player can view the hint of each question
                when place the cursor mouse in the answer box field.
            </p>
        </div>
    </div>
    <div class="mt-4 row d-flex justify-content-center">
        <img id="example" src="{% static 'game/example.png' %}" alt="Thor Icon" height="500" width="auto" style="padding-top:1%">
    </div>
    <div class="mt-4 row d-flex justify-content-center" style="margin-bottom: 10%">
        <button id="howtobutton" type="button" class="howto btn-light btn-lg col-11" onclick="window.location.href='{% url 'game:topic' %}'">Play Now</button>
    </div>
</div>
{% endblock %}

game/templates/game/preview_form.html
{% extends "game/base.html" %}
{% block content %}
{% load static boxed_answer %}

 <link rel = "stylesheet" type = "text/css" href="{% static 'game/preview_form_style.css' %}">

<h1 class="mt-5 pt-5 head">Preview Form</h1>
<div class="main_focus container">
    <h4 id="pre-topic">Topic: {{question.topic}}</h4>
    <h4 id="pre-diff"> Difficulty: {{question.difficulty|title}}</h4>
    <h3 id="pre-question" class="title">{{question.question_title}}</h3>
    <br>
    <p id="pre-question-box" class="q_text">{{question.question_text|boxed}}</p>
</div>

<div class="button-group">
    <a id="edit-form" class="button" href="{% url 'game:edit' question.id %}">Back to Edit Form</a>
    <a id="save-and-create" class="button" href="{% url 'game:form' %}">Save and Create Another</a>
    <a id="save-question" class="button" href="{% url 'game:home' %}">Save</a>
    <a id="discard-form" class="button" href="{% url 'game:discard' question.id %}">Discard</a>

</div>

{% endblock %}

game/templates/game/topic.html
{% extends "game/base.html" %}

{% block content %}
{% load static %}
<link rel = "stylesheet" type = "text/css" href="{% static 'game/topic_page_style.css' %}">

<h1 class="mt-5 pt-5 topic">Pick your topic</h1>
<div class="mt-4 container">
    <div class="mt-5 row">
        {% for t in topic %}
        <div class="col-4">
            <button type="button" class="m-2 mt-4 topic btn-lg" onclick="window.location.href='{% url 'game:question' t.id %}'">{{ t }}</button>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock  %}